### ISSUE TITLE
Can we get an actual build of these?

### ISSUE THREAD

**Issue by mattHorrigan** [reduzent/pd-mrpeach#1]
Hello!

Is a compiled version available?  I see .c files and help files, but no .pd files.

**Comment by reduzent** [comment]
Usually, only the source is checked into git repositories, no binaries. 

I didn't want to go through the trouble of creating a mrpeach release, but I took some objects from this library and made separate Deken releases. You'll be able to find them with Pd through the menu 'Help' -> 'Find externals'. 

You'll find:
 
* osc
* midifile
* slip
